### PR TITLE
Persistent Data Feature

### PR DESCRIPTION
**Pull request by flamendless**
Hi, DearImGui saves the state of windows in an `.ini` file which is automatically loaded upon restart so user interactions with windows persist. This is useful so that user in run-time can move windows to their likings and would not have to repeat the same process upon restart of the application. In my opinion this is more convenient for the purpose of using Slab a debugging/developer tool.

I have tested the changes using the `main.lua` example and it works fine (moving and resizing of the window).

Also, there are some things I would like to point out. In this prototype PR, the `Window.Begin` returns the `ActiveInstance` table when `SLAB_SHOULD_SAVE` is `true` for optimization. However, I also think that instead of returning a table for serialization, we could perhaps move the serialization straight at the end of `Window.Begin` API.

The `serializer.lua` is currently unoptimized, I will make a follow-up for that.

Let me know what you think.

### CODE REVIEW

**Comment by coding-jackalope** [comment]
Hi, thanks for looking into this. This is definitely a feature I have on my TODO list but never got around to it. I will go ahead and move it up in priority.

One thing I have been trying to avoid with Slab is having any library dependencies. This is dependent on the license and potential support the external library will receive in any future releases. However, there is already a method to serialize data in an INI format that could be used for this feature.

Saving the window state is a good beginning, but I am thinking of a more robust system that can be extended to all controls. Things such as tree item open/close states could prove useful in serializing as well.

I will begin working on this feature soon. This pull request can provide some insight on how to go about implementing this feature and will pull in any relevant changes. Thanks again for your hard work!

**Comment by flamendless** [comment]
Just curious, is it easier to encode and decode lua data to INI instead of serializing it to lua table as well?

I agree. All state should be saved as well as with DearImGui, but I haven't got the chance to study the inner workings of Slab to understand those properties so I've started with window states.

Alright thanks for the prioritization of this feature.

Also, in DearImGui it is allowed to set a flag to not allow a window and its inner states to "persist" (I forgot the name of the flag), which should also must be considered in next update.

**Comment by coding-jackalope** [comment]
I suggested INI since there is already support in Slab to serialize shallow tables in this format, which may be enough for saving simple state.

Is the flag you are referring to ImGuiWindowFlags_NoSavedSettings? If so, this is something I can add along with this feature.

**Comment by flamendless** [comment]
Oh. Didn't know Slab has serialization already.

Yes that's it

**Comment by coding-jackalope** [comment]
This feature has been implemented in release v0.6.4.

**Pull request closed without merging**
